# Generated by Django 5.2 on 2025-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='media',
            field=models.FileField(upload_to='clients/'),
        ),
    ]
